version: "3.8"
services:
  mongo:
    networks:
      - mynet
    container_name: mongo 
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.9.2
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - mynet
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
  kibana:
    container_name: kibana
    image: kibana:7.9.2
    volumes:
      - kibana_data:/usr/share/kibana/data
    networks:
      - mynet
    ports:
      - '5601:5601'
  fineconversionbackend:
    container_name: fineconversionbackend
    image: fineconversionbackend
    volumes:
      - fineconversionbackend_data:/usr/share/fineconversionbackend/data
    networks:
      - mynet
    ports:
      - '3000:3000'
    environment:
      - DEBUG=1
      - MONGODB_HOST=mongo
      - ELASTICSEARCH_HOST =elasticsearch
    depends_on:
      - mongo
      - elasticsearch
      - kibana
volumes:
  mongo_data:
  elasticsearch_data:
  kibana_data:
  fineconversionbackend_data:
networks:
  mynet:
    driver: bridge

